packages:
  - apps/*
  - packages/*
  - 'packages/cms/*'

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - husky
  - less
  - msw
  - nx
  - sharp
  - unrs-resolver
