/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    offers: Offer;
    'flash-sales': FlashSale;
    agencies: Agency;
    agents: Agent;
    'business-metrics': BusinessMetric;
    ingestions: Ingestion;
    subscribers: Subscriber;
    tenants: Tenant;
    users: User;
    notifications: Notification;
    'dynamic-routes': DynamicRoute;
    media: Media;
    'blog-posts': BlogPost;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    offers: OffersSelect<false> | OffersSelect<true>;
    'flash-sales': FlashSalesSelect<false> | FlashSalesSelect<true>;
    agencies: AgenciesSelect<false> | AgenciesSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    'business-metrics': BusinessMetricsSelect<false> | BusinessMetricsSelect<true>;
    ingestions: IngestionsSelect<false> | IngestionsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'dynamic-routes': DynamicRoutesSelect<false> | DynamicRoutesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Gestão estratégica de pacotes turísticos e programas de hospitalidade.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: string;
  title: string;
  /**
   * Ruta SEO inmutable.
   */
  slug?: string | null;
  type: 'package' | 'program' | 'promo';
  audience: 'public' | 'agents' | 'elite';
  status: 'draft' | 'published' | 'sold_out';
  /**
   * Resumo da proposta de valor comercial.
   */
  description: string;
  /**
   * Mínimo de noites.
   */
  nightsCount?: number | null;
  /**
   * Preço base net.
   */
  basePrice: number;
  currency?: ('BRL' | 'USD' | 'ARS') | null;
  /**
   * Vagas totais (0 = ilimitado).
   */
  maxCapacity?: number | null;
  inclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Propriedade proprietária desta oferta.
   */
  tenant: string | Tenant;
  /**
   * Imagem de impacto para o card (LCP Optimized).
   */
  heroAsset: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestão centralizada de identidades de propriedade, DNA de marca e ativos vigentes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  /**
   * Identificador inalterável para API (Inamovível).
   */
  slug?: string | null;
  /**
   * Domínio DNS autorizado para handshake de segurança.
   */
  domain: string;
  status: 'active' | 'maintenance' | 'suspended';
  heroConfig: {
    /**
     * Selecione o vídeo principal da Bóveda S3.
     */
    activeHeroVideo: string | Media;
    /**
     * Imagem de fallback (Poster) para o vídeo.
     */
    activeHeroPoster: string | Media;
    /**
     * Áudio ambiental para o loop cinematográfico.
     */
    activeHeroAudio?: (string | null) | Media;
  };
  /**
   * Token Primary (Header/UI).
   */
  primaryColor: string;
  /**
   * Token Accent (Glow/P33).
   */
  accentColor: string;
  logo: string | Media;
  favicon?: (string | null) | Media;
  socialDNA?: {
    instagram?: string | null;
    facebook?: string | null;
    whatsapp?: string | null;
  };
  seoMaster?: {
    globalMetaTitle?: string | null;
    globalMetaDescription?: string | null;
  };
  /**
   * Ativa o sistema de reputação e artefatos nesta propriedade.
   */
  enableGamification?: boolean | null;
  /**
   * Multiplicador de XP para eventos táticos neste Tenant.
   */
  baseExperienceMultiplier?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestão de ativos binários de alta fidelidade sincronizados com S3 Cluster.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Crítico para SEO. Texto alternativo descriptivo.
   */
  alt: string;
  /**
   * Categorização para o orquestrador de visuais dinâmicos.
   */
  assetContext: 'branding' | 'interior' | 'event' | 'social' | 'ai-synth' | 'system';
  /**
   * Informação editorial extendida.
   */
  caption?: string | null;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'hero-cinematic'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Gestão automatizada de ofertas de curta duração e alta conversão.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flash-sales".
 */
export interface FlashSale {
  id: string;
  title: string;
  /**
   * ID Semântico para rumbos SEO.
   */
  slug?: string | null;
  audience: 'public' | 'agents' | 'vip';
  status: 'draft' | 'active' | 'sold_out' | 'expired';
  /**
   * Define o tema visual do ativo.
   */
  vibe: 'day' | 'night';
  /**
   * Micro-copy de impacto tático.
   */
  description: string;
  /**
   * Preço cheio.
   */
  basePrice: number;
  /**
   * Desconto (%)
   */
  discountValue: number;
  /**
   * Lote total.
   */
  totalInventory: number;
  /**
   * Disponível agora.
   */
  currentStock: number;
  expiresAt: string;
  /**
   * Imagem de alta fidelidade para impacto visual.
   */
  heroAsset: string | Media;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Diretório central de operadoras e agências de viagens verificadas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies".
 */
export interface Agency {
  id: string;
  brandName: string;
  legalName: string;
  jurisdiction: 'BR' | 'CL' | 'INTL';
  taxId: string;
  iataCode?: string | null;
  /**
   * Isotipo para co-branding y flyers.
   */
  logo: string | Media;
  /**
   * Valor total de reservas geradas (R$).
   */
  totalYield?: number | null;
  /**
   * Comissões devengadas pendentes de pagamento.
   */
  pendingCommission?: number | null;
  /**
   * Índice de credibilidade (0-100).
   */
  trustScore?: number | null;
  tier: 'platinum' | 'gold' | 'silver' | 'bronze';
  status: 'active' | 'review' | 'blocked';
  tenant: string | Tenant;
  /**
   * Registro inalterável de notas técnicas.
   */
  internalObservations?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestão de consultores individuais e seu histórico na Red de Alianzas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: string;
  fullName: string;
  status: 'active' | 'inactive' | 'blacklisted';
  email: string;
  phone?: string | null;
  /**
   * Vinculação ativa no ecossistema B2B.
   */
  currentAgency: string | Agency;
  employmentHistory?:
    | {
        agency: string | Agency;
        reasonForDeparture?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        id?: string | null;
      }[]
    | null;
  tenant: string | Tenant;
  performanceMetrics?: {
    dealsClosed?: number | null;
    totalRevenueGenerated?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Ledger de transações com motor de propagação de reputação ativo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-metrics".
 */
export interface BusinessMetric {
  id: string;
  type: 'booking_success' | 'booking_failed' | 'inquiry' | 'commission_payout';
  status: 'processed' | 'pending' | 'error';
  /**
   * Valor financeiro bruto.
   */
  value: number;
  currency: 'BRL' | 'USD' | 'ARS';
  /**
   * Margem de lucro (%)
   */
  margin: number;
  agency: string | Agency;
  client: string | User;
  agent?: (string | null) | Agent;
  offer?: (string | null) | Offer;
  traceId?: string | null;
  tenant: string | Tenant;
  /**
   * Dados forenses do processamento.
   */
  metaData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestão de identidades soberanas e reactor de reputação P33.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  email: string;
  role: 'developer' | 'admin' | 'operator' | 'sponsor' | 'guest';
  /**
   * Perímetro soberano de propriedade.
   */
  tenant: string | Tenant;
  /**
   * Calculado pelo Math Engine.
   */
  level?: number | null;
  /**
   * Total de RazTokens (XP) acumulados.
   */
  experiencePoints: number;
  operatorMetadata?: {
    agency: string | Agency;
    accessLevel?: ('manager' | 'consultant') | null;
  };
  guestMetadata?: {
    preferredLanguage?: string | null;
    discoverySource?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Pipeline central de captura e processamento de inteligência de dados.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingestions".
 */
export interface Ingestion {
  id: string;
  subject: string;
  priority?: ('critical' | 'high' | 'normal') | null;
  type: 'document' | 'image' | 'audio' | 'text';
  channel: 'web' | 'whatsapp' | 'api';
  status: 'pending' | 'processing' | 'processed' | 'error';
  pipelineMetrics?: {
    nodesInjected?: number | null;
    duplicatesSkipped?: number | null;
    failedRows?: number | null;
    executionTimeMs?: number | null;
  };
  issues?:
    | {
        row?: number | null;
        error?: string | null;
        /**
         * Payload original da linha con erro.
         */
        data?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  traceId?: string | null;
  tenant: string | Tenant;
  /**
   * Snapshot JSON do resultado.
   */
  processedData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  senderInfo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestão centralizada de identidades e jornada de conversão do hóspede.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: string;
  /**
   * Utilizado para personalização no Marketing Cloud.
   */
  name?: string | null;
  email: string;
  status: 'active' | 'unsubscribed' | 'bounced' | 'quarantine';
  engagementLevel?: ('newbie' | 'engaged' | 'loyalist') | null;
  /**
   * Canal de origen (Ej: hero-form, Silo-C Ingest).
   */
  source?: string | null;
  /**
   * Autorização para comunicações.
   */
  consentMarketing: boolean;
  /**
   * Autorização para behavioral tracking.
   */
  consentAnalytics?: boolean | null;
  /**
   * Carimbo de tempo da última alteração de consentimento.
   */
  consentTimestamp?: string | null;
  emailsSentCount?: number | null;
  /**
   * Porcentagem de abertura.
   */
  openRate?: number | null;
  lastEngagementDate?: string | null;
  /**
   * Payload técnico forense (Trace ID, IP, Client Context).
   */
  metaData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Perímetro proprietário desta identidade.
   */
  tenant: string | Tenant;
  unsubscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro soberano de sinais operacionais e alertas de infraestrutura.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  subject: string;
  category: 'security' | 'ops' | 'revenue' | 'comms' | 'infra';
  priority: 'low' | 'high' | 'critical';
  source: string;
  /**
   * Detalhes forenses da sinalização.
   */
  message: string;
  /**
   * Link para resolução imediata.
   */
  actionUrl?: string | null;
  traceId?: string | null;
  /**
   * IP ou Contexto do despachador.
   */
  originNode?: string | null;
  isRead?: boolean | null;
  /**
   * Destinatário opcional.
   */
  recipient?: (string | null) | User;
  /**
   * Payload técnico bruto.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Perímetro proprietário.
   */
  tenant: string | Tenant;
  /**
   * Data do Auto-Purge industrial.
   */
  expiresAt?: string | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pontos de acesso inteligentes e mapeamento de rumbos dinâmicos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dynamic-routes".
 */
export interface DynamicRoute {
  id: string;
  internalReference: string;
  /**
   * hotel.com/r/[routeKey]
   */
  routeKey: string;
  /**
   * URL de destino padrão se as regras não forem atendidas.
   */
  fallbackUrl: string;
  conditionalRules?:
    | {
        startTime?: string | null;
        endTime?: string | null;
        destinationUrl: string;
        /**
         * Nível mínimo do Protocolo 33 para ativar esta regra.
         */
        requiredLoyaltyLevel?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Perímetro proprietário do ponto.
   */
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestão da narrativa e inteligência editorial do Santuário.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  /**
   * Propriedade detentora desta narrativa.
   */
  tenant: string | Tenant;
  title: string;
  /**
   * Permalink inalterável após publicação.
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Resumo crítico para meta-tags SEO.
   */
  description: string;
  author: string | User;
  publishedDate: string;
  status: 'draft' | 'published';
  /**
   * Define o tema visual no Portal.
   */
  vibe: 'day' | 'night';
  /**
   * Taxonomia indexada por busca semântica.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Asset visual de alta fidelidade para LCP.
   */
  ogImage: string | Media;
  /**
   * Cálculo de densidade (wpm: 225).
   */
  readingTime?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catálogo de infraestruturas digitais e ativos de alta engenharia.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  slug: string;
  description: string;
  /**
   * Ativo visual de alta fidelidade (S3 Vault).
   */
  mainImage: string | Media;
  liveUrl?: string | null;
  codeUrl?: string | null;
  tags: {
    tag: string;
    id?: string | null;
  }[];
  introduction: {
    heading: string;
    body: string;
  };
  tech_stack: {
    technology: string;
    id?: string | null;
  }[];
  elite_options?:
    | {
        name: string;
        detail: string;
        id?: string | null;
      }[]
    | null;
  backend_architecture: {
    title: string;
    description?: string | null;
    features?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
  };
  branding: {
    /**
     * Cor de acento (Space OKLCH support).
     */
    primary_color: string;
    layout_style: 'minimal' | 'immersive' | 'editorial' | 'corporate' | 'brutalist';
  };
  reputationWeight: number;
  tenant: string | Tenant;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'offers';
        value: string | Offer;
      } | null)
    | ({
        relationTo: 'flash-sales';
        value: string | FlashSale;
      } | null)
    | ({
        relationTo: 'agencies';
        value: string | Agency;
      } | null)
    | ({
        relationTo: 'agents';
        value: string | Agent;
      } | null)
    | ({
        relationTo: 'business-metrics';
        value: string | BusinessMetric;
      } | null)
    | ({
        relationTo: 'ingestions';
        value: string | Ingestion;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: string | Subscriber;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'dynamic-routes';
        value: string | DynamicRoute;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  audience?: T;
  status?: T;
  description?: T;
  nightsCount?: T;
  basePrice?: T;
  currency?: T;
  maxCapacity?: T;
  inclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  tenant?: T;
  heroAsset?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flash-sales_select".
 */
export interface FlashSalesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  audience?: T;
  status?: T;
  vibe?: T;
  description?: T;
  basePrice?: T;
  discountValue?: T;
  totalInventory?: T;
  currentStock?: T;
  expiresAt?: T;
  heroAsset?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies_select".
 */
export interface AgenciesSelect<T extends boolean = true> {
  brandName?: T;
  legalName?: T;
  jurisdiction?: T;
  taxId?: T;
  iataCode?: T;
  logo?: T;
  totalYield?: T;
  pendingCommission?: T;
  trustScore?: T;
  tier?: T;
  status?: T;
  tenant?: T;
  internalObservations?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  fullName?: T;
  status?: T;
  email?: T;
  phone?: T;
  currentAgency?: T;
  employmentHistory?:
    | T
    | {
        agency?: T;
        reasonForDeparture?: T;
        startDate?: T;
        endDate?: T;
        id?: T;
      };
  tenant?: T;
  performanceMetrics?:
    | T
    | {
        dealsClosed?: T;
        totalRevenueGenerated?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-metrics_select".
 */
export interface BusinessMetricsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  value?: T;
  currency?: T;
  margin?: T;
  agency?: T;
  client?: T;
  agent?: T;
  offer?: T;
  traceId?: T;
  tenant?: T;
  metaData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingestions_select".
 */
export interface IngestionsSelect<T extends boolean = true> {
  subject?: T;
  priority?: T;
  type?: T;
  channel?: T;
  status?: T;
  pipelineMetrics?:
    | T
    | {
        nodesInjected?: T;
        duplicatesSkipped?: T;
        failedRows?: T;
        executionTimeMs?: T;
      };
  issues?:
    | T
    | {
        row?: T;
        error?: T;
        data?: T;
        id?: T;
      };
  traceId?: T;
  tenant?: T;
  processedData?: T;
  senderInfo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  status?: T;
  engagementLevel?: T;
  source?: T;
  consentMarketing?: T;
  consentAnalytics?: T;
  consentTimestamp?: T;
  emailsSentCount?: T;
  openRate?: T;
  lastEngagementDate?: T;
  metaData?: T;
  tenant?: T;
  unsubscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  status?: T;
  heroConfig?:
    | T
    | {
        activeHeroVideo?: T;
        activeHeroPoster?: T;
        activeHeroAudio?: T;
      };
  primaryColor?: T;
  accentColor?: T;
  logo?: T;
  favicon?: T;
  socialDNA?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        whatsapp?: T;
      };
  seoMaster?:
    | T
    | {
        globalMetaTitle?: T;
        globalMetaDescription?: T;
      };
  enableGamification?: T;
  baseExperienceMultiplier?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  role?: T;
  tenant?: T;
  level?: T;
  experiencePoints?: T;
  operatorMetadata?:
    | T
    | {
        agency?: T;
        accessLevel?: T;
      };
  guestMetadata?:
    | T
    | {
        preferredLanguage?: T;
        discoverySource?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  subject?: T;
  category?: T;
  priority?: T;
  source?: T;
  message?: T;
  actionUrl?: T;
  traceId?: T;
  originNode?: T;
  isRead?: T;
  recipient?: T;
  metadata?: T;
  tenant?: T;
  expiresAt?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dynamic-routes_select".
 */
export interface DynamicRoutesSelect<T extends boolean = true> {
  internalReference?: T;
  routeKey?: T;
  fallbackUrl?: T;
  conditionalRules?:
    | T
    | {
        startTime?: T;
        endTime?: T;
        destinationUrl?: T;
        requiredLoyaltyLevel?: T;
        id?: T;
      };
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  assetContext?: T;
  caption?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'hero-cinematic'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  content?: T;
  description?: T;
  author?: T;
  publishedDate?: T;
  status?: T;
  vibe?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  ogImage?: T;
  readingTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  mainImage?: T;
  liveUrl?: T;
  codeUrl?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  introduction?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  tech_stack?:
    | T
    | {
        technology?: T;
        id?: T;
      };
  elite_options?:
    | T
    | {
        name?: T;
        detail?: T;
        id?: T;
      };
  backend_architecture?:
    | T
    | {
        title?: T;
        description?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
      };
  branding?:
    | T
    | {
        primary_color?: T;
        layout_style?: T;
      };
  reputationWeight?: T;
  tenant?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}